/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.ControladorMetodosCerrados;
import modelos.ModeloMetodosCerrados;

/**
 *
 * @author jhosu
 */
public class MenuMetodosCerrados extends javax.swing.JPanel {

    /**
     * Creates new form Prueba
     */
    public MenuMetodosCerrados() {
        initComponents();
        modelos.ModeloMetodosCerrados modelo = new ModeloMetodosCerrados(this);
        controladores.ControladorMetodosCerrados controlador = new ControladorMetodosCerrados(modelo);
        setControlador(controlador);
    }   
    

  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFondoMC = new javax.swing.JPanel();
        ContenedorlVentanaMenu = new javax.swing.JPanel();
        pnlTittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBiseccion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReglaFalsa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        BtnVolver = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPFondoMC.setBackground(new java.awt.Color(204, 204, 204));
        jPFondoMC.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPFondoMC.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPFondoMC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContenedorlVentanaMenu.setBackground(new java.awt.Color(227, 252, 249));
        ContenedorlVentanaMenu.setPreferredSize(new java.awt.Dimension(1280, 720));
        ContenedorlVentanaMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTittle.setBackground(new java.awt.Color(72, 137, 172));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Métodos Cerrados");

        javax.swing.GroupLayout pnlTittleLayout = new javax.swing.GroupLayout(pnlTittle);
        pnlTittle.setLayout(pnlTittleLayout);
        pnlTittleLayout.setHorizontalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTittleLayout.setVerticalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContenedorlVentanaMenu.add(pnlTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 104, -1, -1));

        btnBiseccion.setBackground(new java.awt.Color(172, 229, 246));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Método Bisección");

        javax.swing.GroupLayout btnBiseccionLayout = new javax.swing.GroupLayout(btnBiseccion);
        btnBiseccion.setLayout(btnBiseccionLayout);
        btnBiseccionLayout.setHorizontalGroup(
            btnBiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBiseccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBiseccionLayout.setVerticalGroup(
            btnBiseccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBiseccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContenedorlVentanaMenu.add(btnBiseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 305, -1, -1));

        btnReglaFalsa.setBackground(new java.awt.Color(172, 229, 246));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Método Regla Falsa");

        javax.swing.GroupLayout btnReglaFalsaLayout = new javax.swing.GroupLayout(btnReglaFalsa);
        btnReglaFalsa.setLayout(btnReglaFalsaLayout);
        btnReglaFalsaLayout.setHorizontalGroup(
            btnReglaFalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReglaFalsaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnReglaFalsaLayout.setVerticalGroup(
            btnReglaFalsaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReglaFalsaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContenedorlVentanaMenu.add(btnReglaFalsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 305, -1, -1));

        btnVolver.setBackground(new java.awt.Color(172, 229, 246));

        BtnVolver.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        BtnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnVolver.setText("Volver");

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        ContenedorlVentanaMenu.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 481, 210, -1));

        jPFondoMC.add(ContenedorlVentanaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondoMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPFondoMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnVolver;
    public javax.swing.JPanel ContenedorlVentanaMenu;
    public javax.swing.JPanel btnBiseccion;
    public javax.swing.JPanel btnReglaFalsa;
    public javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPFondoMC;
    private javax.swing.JPanel pnlTittle;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorMetodosCerrados controlador){
        
        btnBiseccion.addMouseListener(controlador);
        btnReglaFalsa.addMouseListener(controlador);
        btnVolver.addMouseListener(controlador);
        
    }

}
