/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorVistaPrincipal;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import modelos.ModeloVistaPrincipal;
//import javax.swing.ImageIcon;

/**
 *
 * @author jhosu
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        //Configuraciones de la vista.
        //[245,247,250] Primera elección de color del panel
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("METODOS NUMERICOS");

        modelos.ModeloVistaPrincipal modelo = new ModeloVistaPrincipal(this);
        controladores.ControladorVistaPrincipal controlador = new ControladorVistaPrincipal(modelo);

        setControlador(controlador);
        
        Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/IconMetodosNumApp.png"));
        setIconImage(icono);
    }
    
//    @Override
//    public Image getIconImage(){
//        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("C:\\Users\\jhosu\\OneDrive\\Documents\\TareasUMG\\MetodosNumericosProject\\MetodosNumericos\\src\\imagenes\\IconAppMN.png"));
//        return retValue;
//    }
    
    
    
    public JPanel getMiContenedor() {
    return this.pnlContenedor;
}
    
    public JPanel getMiJPanel() {
    return this.panelMenu;
}   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoVentana = new javax.swing.JPanel();
        pnlContenedor = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        pnlTittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMetodoCerrado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMetodosAbiertos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRaicesPolinomios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEcuaciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 720));

        pnlFondoVentana.setBackground(new java.awt.Color(204, 204, 204));
        pnlFondoVentana.setToolTipText("");
        pnlFondoVentana.setPreferredSize(new java.awt.Dimension(1380, 720));
        pnlFondoVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(227, 252, 249));
        panelMenu.setPreferredSize(new java.awt.Dimension(1280, 720));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTittle.setBackground(new java.awt.Color(134, 166, 222));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Métodos Numéricos");

        javax.swing.GroupLayout pnlTittleLayout = new javax.swing.GroupLayout(pnlTittle);
        pnlTittle.setLayout(pnlTittleLayout);
        pnlTittleLayout.setHorizontalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE))
        );
        pnlTittleLayout.setVerticalGroup(
            pnlTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        panelMenu.add(pnlTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 140));

        btnMetodoCerrado.setBackground(new java.awt.Color(172, 229, 246));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Métodos Cerrados");

        javax.swing.GroupLayout btnMetodoCerradoLayout = new javax.swing.GroupLayout(btnMetodoCerrado);
        btnMetodoCerrado.setLayout(btnMetodoCerradoLayout);
        btnMetodoCerradoLayout.setHorizontalGroup(
            btnMetodoCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMetodoCerradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnMetodoCerradoLayout.setVerticalGroup(
            btnMetodoCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMetodoCerradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenu.add(btnMetodoCerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 270, 120));

        btnMetodosAbiertos.setBackground(new java.awt.Color(172, 229, 246));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Métodos Abiertos");

        javax.swing.GroupLayout btnMetodosAbiertosLayout = new javax.swing.GroupLayout(btnMetodosAbiertos);
        btnMetodosAbiertos.setLayout(btnMetodosAbiertosLayout);
        btnMetodosAbiertosLayout.setHorizontalGroup(
            btnMetodosAbiertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMetodosAbiertosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnMetodosAbiertosLayout.setVerticalGroup(
            btnMetodosAbiertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMetodosAbiertosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenu.add(btnMetodosAbiertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 270, 120));

        btnRaicesPolinomios.setBackground(new java.awt.Color(172, 229, 246));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Raices de Polinomios");

        javax.swing.GroupLayout btnRaicesPolinomiosLayout = new javax.swing.GroupLayout(btnRaicesPolinomios);
        btnRaicesPolinomios.setLayout(btnRaicesPolinomiosLayout);
        btnRaicesPolinomiosLayout.setHorizontalGroup(
            btnRaicesPolinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaicesPolinomiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btnRaicesPolinomiosLayout.setVerticalGroup(
            btnRaicesPolinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaicesPolinomiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelMenu.add(btnRaicesPolinomios, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 250, 70));

        btnEcuaciones.setBackground(new java.awt.Color(172, 229, 246));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ecuaciones");

        javax.swing.GroupLayout btnEcuacionesLayout = new javax.swing.GroupLayout(btnEcuaciones);
        btnEcuaciones.setLayout(btnEcuacionesLayout);
        btnEcuacionesLayout.setHorizontalGroup(
            btnEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEcuacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btnEcuacionesLayout.setVerticalGroup(
            btnEcuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEcuacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.add(btnEcuaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        pnlContenedor.add(panelMenu, java.awt.BorderLayout.CENTER);

        pnlFondoVentana.add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1280, 720));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnVolver.setBackground(new java.awt.Color(102, 204, 255));
        btnVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnVolverMNumApp.png"))); // NOI18N
        btnVolver.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 445, Short.MAX_VALUE))
        );

        pnlFondoVentana.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondoVentana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnEcuaciones;
    public javax.swing.JPanel btnMetodoCerrado;
    public javax.swing.JPanel btnMetodosAbiertos;
    public javax.swing.JPanel btnRaicesPolinomios;
    public javax.swing.JPanel btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFondoVentana;
    private javax.swing.JPanel pnlTittle;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVistaPrincipal controlador){
        
        btnMetodoCerrado.addMouseListener(controlador);
        btnMetodosAbiertos.addMouseListener(controlador);
        btnRaicesPolinomios.addMouseListener(controlador);
        btnEcuaciones.addMouseListener(controlador);
        btnVolver.addMouseListener(controlador);
    }




}
