/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.ControladorMetodoRaicesMultiples;
import modelos.ModeloMetodoRaicesMultiples;

/**
 *
 * @author merar
 */
public class VistaMetodoRaicesMultiples extends javax.swing.JPanel {

    /**
     * Creates new form VistaMetodoRaicesMultliples
     */
    public VistaMetodoRaicesMultiples() {
        initComponents();
        
        ModeloMetodoRaicesMultiples modelo = new ModeloMetodoRaicesMultiples(this);
        ControladorMetodoRaicesMultiples controlador = new ControladorMetodoRaicesMultiples(modelo);
        
        setControlador(controlador);
        
       jLabelResultadoXR.setVisible(false);
       jCombResultXR.setVisible(false);
       btnLimpiar.setVisible(false);
       labelXi.setVisible(false);
       labelHastaX.setVisible(false);
       txtXI.setVisible(false);
       txtHastaX.setVisible(false);
       panelTabla.setVisible(false);
       btnResolver.setVisible(false);
       
       btnGroupIntervalos.add(radBtnConIntervalo);
       btnGroupIntervalos.add(radBtnSinIntervalo);
       
       
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupIntervalos = new javax.swing.ButtonGroup();
        fondoRM = new javax.swing.JPanel();
        txtFuncion = new javax.swing.JTextField();
        fondotitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelXi = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCombResultXR = new javax.swing.JComboBox<>();
        jLabelResultadoXR = new javax.swing.JLabel();
        btnResolver = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContainerRM = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtXI = new javax.swing.JTextField();
        radBtnConIntervalo = new javax.swing.JRadioButton();
        radBtnSinIntervalo = new javax.swing.JRadioButton();
        txtHastaX = new javax.swing.JTextField();
        labelHastaX = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        fondoRM.setBackground(new java.awt.Color(227, 252, 249));
        fondoRM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFuncion.setBackground(new java.awt.Color(204, 204, 204));
        txtFuncion.setForeground(new java.awt.Color(0, 0, 0));
        fondoRM.add(txtFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 320, 250, 50));

        fondotitulo.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metodo Raices Multiples ");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 27));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 27));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 27));

        javax.swing.GroupLayout fondotituloLayout = new javax.swing.GroupLayout(fondotitulo);
        fondotitulo.setLayout(fondotituloLayout);
        fondotituloLayout.setHorizontalGroup(
            fondotituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondotituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        fondotituloLayout.setVerticalGroup(
            fondotituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondotituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoRM.add(fondotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Función F(x)");
        fondoRM.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 220, 37));

        labelXi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelXi.setForeground(new java.awt.Color(0, 0, 0));
        labelXi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelXi.setText("Xi");
        fondoRM.add(labelXi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 110, 29));

        panelTabla.setBackground(new java.awt.Color(204, 204, 204));
        panelTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("X");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("F(X)");

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondoRM.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, 30));

        jCombResultXR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCombResultXR.setName(""); // NOI18N
        jCombResultXR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombResultXRActionPerformed(evt);
            }
        });
        fondoRM.add(jCombResultXR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 42));

        jLabelResultadoXR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelResultadoXR.setForeground(new java.awt.Color(0, 0, 0));
        jLabelResultadoXR.setText("XR Obtenido");
        fondoRM.add(jLabelResultadoXR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, -1));

        btnResolver.setBackground(new java.awt.Color(0, 153, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESOLVER");

        javax.swing.GroupLayout btnResolverLayout = new javax.swing.GroupLayout(btnResolver);
        btnResolver.setLayout(btnResolverLayout);
        btnResolverLayout.setHorizontalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnResolverLayout.setVerticalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnResolverLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoRM.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 100, -1));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tableContainerRM.setBackground(new java.awt.Color(204, 204, 204));
        tableContainerRM.setLayout(new javax.swing.BoxLayout(tableContainerRM, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(tableContainerRM);

        fondoRM.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 327, 730, 350));

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 204));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LIMPIAR");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondoRM.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 570, 100, 40));

        txtXI.setBackground(new java.awt.Color(204, 204, 204));
        fondoRM.add(txtXI, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 80, 40));

        radBtnConIntervalo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radBtnConIntervalo.setForeground(new java.awt.Color(0, 0, 0));
        radBtnConIntervalo.setText("Con intervalo");
        fondoRM.add(radBtnConIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, -1, -1));

        radBtnSinIntervalo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        radBtnSinIntervalo.setForeground(new java.awt.Color(0, 0, 0));
        radBtnSinIntervalo.setText("Sin intervalo");
        fondoRM.add(radBtnSinIntervalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, -1, -1));

        txtHastaX.setBackground(new java.awt.Color(204, 204, 204));
        fondoRM.add(txtHastaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 80, 40));

        labelHastaX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelHastaX.setForeground(new java.awt.Color(0, 0, 0));
        labelHastaX.setText("X Hasta:");
        fondoRM.add(labelHastaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCombResultXRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombResultXRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombResultXRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btnGroupIntervalos;
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnResolver;
    private javax.swing.JPanel fondoRM;
    private javax.swing.JPanel fondotitulo;
    public javax.swing.JComboBox<String> jCombResultXR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelResultadoXR;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelHastaX;
    public javax.swing.JLabel labelXi;
    private javax.swing.JPanel panelTabla;
    public javax.swing.JRadioButton radBtnConIntervalo;
    public javax.swing.JRadioButton radBtnSinIntervalo;
    public javax.swing.JPanel tableContainerRM;
    public javax.swing.JTextField txtFuncion;
    public javax.swing.JTextField txtHastaX;
    public javax.swing.JTextField txtXI;
    // End of variables declaration//GEN-END:variables

public void setControlador(ControladorMetodoRaicesMultiples controlador){
    
    btnResolver.addMouseListener(controlador); 
    btnLimpiar.addMouseListener(controlador);
    radBtnConIntervalo.addMouseListener(controlador);
    radBtnSinIntervalo.addMouseListener(controlador);
    
    
}



}
