/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.ControladorMetodoRaicesMultiples;
import modelos.ModeloMetodoRaicesMultiples;

/**
 *
 * @author merar
 */
public class VistaMetodoRaicesMultiples extends javax.swing.JPanel {

    /**
     * Creates new form VistaMetodoRaicesMultliples
     */
    public VistaMetodoRaicesMultiples() {
        initComponents();
        
        ModeloMetodoRaicesMultiples modelo = new ModeloMetodoRaicesMultiples();
        ControladorMetodoRaicesMultiples controlador = new ControladorMetodoRaicesMultiples(modelo);
        
        setControlador(controlador);
        
       txtFuncion.setVisible(false);
       
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoRM = new javax.swing.JPanel();
        txtFuncion = new javax.swing.JTextField();
        fondotitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrimeraDerivada = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSegundaDerivada = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCombResultXR = new javax.swing.JComboBox<>();
        jLabelResultadoXR = new javax.swing.JLabel();
        btnResolver = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContainerRM = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        fondoRM.setBackground(new java.awt.Color(227, 252, 249));
        fondoRM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondoRM.add(txtFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 207, 34));

        fondotitulo.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metodo Raices Multiples ");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 27));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 27));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 27));

        javax.swing.GroupLayout fondotituloLayout = new javax.swing.GroupLayout(fondotitulo);
        fondotitulo.setLayout(fondotituloLayout);
        fondotituloLayout.setHorizontalGroup(
            fondotituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondotituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        fondotituloLayout.setVerticalGroup(
            fondotituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondotituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoRM.add(fondotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Ingrese Funcion (x)");
        fondoRM.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 207, 37));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Primera Derivada");
        fondoRM.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 191, 29));

        txtPrimeraDerivada.setBackground(new java.awt.Color(255, 255, 255));
        txtPrimeraDerivada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout txtPrimeraDerivadaLayout = new javax.swing.GroupLayout(txtPrimeraDerivada);
        txtPrimeraDerivada.setLayout(txtPrimeraDerivadaLayout);
        txtPrimeraDerivadaLayout.setHorizontalGroup(
            txtPrimeraDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        txtPrimeraDerivadaLayout.setVerticalGroup(
            txtPrimeraDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        fondoRM.add(txtPrimeraDerivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Segunda Derivada");
        fondoRM.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 189, 29));

        txtSegundaDerivada.setBackground(new java.awt.Color(255, 255, 255));
        txtSegundaDerivada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout txtSegundaDerivadaLayout = new javax.swing.GroupLayout(txtSegundaDerivada);
        txtSegundaDerivada.setLayout(txtSegundaDerivadaLayout);
        txtSegundaDerivadaLayout.setHorizontalGroup(
            txtSegundaDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        txtSegundaDerivadaLayout.setVerticalGroup(
            txtSegundaDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        fondoRM.add(txtSegundaDerivada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("X");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("F(X)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        fondoRM.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        jCombResultXR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCombResultXR.setName(""); // NOI18N
        jCombResultXR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombResultXRActionPerformed(evt);
            }
        });
        fondoRM.add(jCombResultXR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 42));

        jLabelResultadoXR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabelResultadoXR.setText("XR Obtenido");
        fondoRM.add(jLabelResultadoXR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 104, -1));

        btnResolver.setBackground(new java.awt.Color(51, 51, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESOLVER");

        javax.swing.GroupLayout btnResolverLayout = new javax.swing.GroupLayout(btnResolver);
        btnResolver.setLayout(btnResolverLayout);
        btnResolverLayout.setHorizontalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        btnResolverLayout.setVerticalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnResolverLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoRM.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tableContainerRM.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tableContainerRMLayout = new javax.swing.GroupLayout(tableContainerRM);
        tableContainerRM.setLayout(tableContainerRMLayout);
        tableContainerRMLayout.setHorizontalGroup(
            tableContainerRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        tableContainerRMLayout.setVerticalGroup(
            tableContainerRMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(tableContainerRM);

        fondoRM.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 327, 730, 350));

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 255));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LIMPIAR");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        fondoRM.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRM, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoRM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCombResultXRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombResultXRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombResultXRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnResolver;
    private javax.swing.JPanel fondoRM;
    private javax.swing.JPanel fondotitulo;
    public javax.swing.JComboBox<String> jCombResultXR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelResultadoXR;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel tableContainerRM;
    public javax.swing.JTextField txtFuncion;
    private javax.swing.JPanel txtPrimeraDerivada;
    private javax.swing.JPanel txtSegundaDerivada;
    // End of variables declaration//GEN-END:variables

public void setControlador(ControladorMetodoRaicesMultiples controlador){
    
    btnResolver.addMouseListener(controlador); 
    btnLimpiar.addMouseListener(controlador);
    
}



}
