package vistas;

import controladores.ControladorMetodoReglaFalsa;
import modelos.ModeloMetodoReglaFalsa;

/**
 *
 * @author jhosu
 */
public class VistaMetodoReglaFalsa extends javax.swing.JPanel {

    /**
     * Creates new form VistaReglaFalsa
     */
    public VistaMetodoReglaFalsa() {
        initComponents();
        modelos.ModeloMetodoReglaFalsa modelo = new ModeloMetodoReglaFalsa(this);
        controladores.ControladorMetodoReglaFalsa controlador = new ControladorMetodoReglaFalsa(modelo);
        setControlador(controlador);
        
        jLabelXRObtenido.setVisible(false);
        jComboBXR.setVisible(false);
        btnLimpiar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorRF = new javax.swing.JPanel();
        jPTittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPTabla = new javax.swing.JScrollPane();
        jPaneScrollTablaRF = new javax.swing.JPanel();
        txtFuction = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIntervaloFA = new javax.swing.JTextField();
        txtIntervaloFB = new javax.swing.JTextField();
        btnResolver = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBXR = new javax.swing.JComboBox<>();
        jLabelXRObtenido = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        contenedorRF.setBackground(new java.awt.Color(227, 252, 249));
        contenedorRF.setMinimumSize(new java.awt.Dimension(1280, 720));
        contenedorRF.setPreferredSize(new java.awt.Dimension(1280, 720));
        contenedorRF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTittle.setBackground(new java.awt.Color(72, 137, 172));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Método Regla Falsa");

        javax.swing.GroupLayout jPTittleLayout = new javax.swing.GroupLayout(jPTittle);
        jPTittle.setLayout(jPTittleLayout);
        jPTittleLayout.setHorizontalGroup(
            jPTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTittleLayout.setVerticalGroup(
            jPTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorRF.add(jPTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 450, 60));

        jPaneScrollTablaRF.setBackground(new java.awt.Color(204, 204, 204));
        jPaneScrollTablaRF.setLayout(new javax.swing.BoxLayout(jPaneScrollTablaRF, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPTabla.setViewportView(jPaneScrollTablaRF);

        contenedorRF.add(jScrollPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 710, 360));

        txtFuction.setBackground(new java.awt.Color(204, 204, 204));
        contenedorRF.add(txtFuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 290, 50));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Ingrese la Función F(x)");
        contenedorRF.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Intervalo F(a)");
        contenedorRF.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Intervalo F(b)");
        contenedorRF.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, -1, -1));

        txtIntervaloFA.setBackground(new java.awt.Color(204, 204, 204));
        contenedorRF.add(txtIntervaloFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 70, 40));

        txtIntervaloFB.setBackground(new java.awt.Color(204, 204, 204));
        contenedorRF.add(txtIntervaloFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 260, 70, 40));

        btnResolver.setBackground(new java.awt.Color(172, 229, 246));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESOLVER");

        javax.swing.GroupLayout btnResolverLayout = new javax.swing.GroupLayout(btnResolver);
        btnResolver.setLayout(btnResolverLayout);
        btnResolverLayout.setHorizontalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnResolverLayout.setVerticalGroup(
            btnResolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorRF.add(btnResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 90, 40));

        contenedorRF.add(jComboBXR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 40));

        jLabelXRObtenido.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabelXRObtenido.setText("XR obtenido:");
        contenedorRF.add(jLabelXRObtenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(172, 229, 246));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Limpiar");

        javax.swing.GroupLayout btnLimpiarLayout = new javax.swing.GroupLayout(btnLimpiar);
        btnLimpiar.setLayout(btnLimpiarLayout);
        btnLimpiarLayout.setHorizontalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLimpiarLayout.setVerticalGroup(
            btnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedorRF.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorRF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnLimpiar;
    public javax.swing.JPanel btnResolver;
    public javax.swing.JPanel contenedorRF;
    public javax.swing.JComboBox<String> jComboBXR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelXRObtenido;
    private javax.swing.JPanel jPTittle;
    public javax.swing.JPanel jPaneScrollTablaRF;
    public javax.swing.JScrollPane jScrollPTabla;
    public javax.swing.JTextField txtFuction;
    public javax.swing.JTextField txtIntervaloFA;
    public javax.swing.JTextField txtIntervaloFB;
    // End of variables declaration//GEN-END:variables

public void setControlador(ControladorMetodoReglaFalsa controlador){
    
    btnResolver.addMouseListener(controlador);
    btnLimpiar.addMouseListener(controlador);
}


}